# Plan configuration
plan:
  # Replace mode:
  # NONE (do not replace existing extensions),
  # REPLACE (replace existing extensions that are not the same version),
  # CLEAN (replace all existing extensions; extensions not extracted from the archive will be removed)
  replace_mode: NONE
  # Backup directory
  backup_dir: "./backup"
  # Temporary directory
  temp_dir: "./temp"
  # Extensions from the archive to include
  include_extensions:
    - name: "ms-python.python"
      version: latest
  # Extensions from the archive to exclude
  exclude_extensions:
    - name: "ms-vscode.vscode-json"
      version: latest

# Source configuration
source:
  # URLs to fetch the extensions archive and manifests from
  archive_url: "https://test.com/vscode-extensions.zip"
  manifest_url: "https://test.com/vscode-extensions.json"
  # Number of retries
  retries: 3

# Deployment configuration
deployment:
  # Target VSCode extensions directory
  target_dir: "C:/Users/Username/.vscode/extensions"
  # Whether to verify extension integrity after extraction
  # NONE (do not verify)
  # WARN (warn if integrity check fails)
  # ERROR (fail if integrity check fails)
  verify_integrity: ERROR
  # Whether to perform a dry run
  dry_run: false

# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR
  level: INFO
  # Log file path (optional)
  file: "./deployer.log"
